### PR TITLE
add opensplice support for cdr serialization

### PR DESCRIPTION
**Pull request by MarcelJordense**
The latest opensource OpenSplice release has been updated with support for cdr serialization. These changes update rosidl_typesupport_opensplice to use this functionality.

### CODE REVIEW

**Comment by Karsten1987** [comment]
I just added a PR to fix the change to `uint8_t`.
https://github.com/MarcelJordense/rosidl_typesupport_opensplice/pull/1

The change is minimal, so that you can either decide to update your original branch or integrate this PR.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5657/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2268/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4677/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5548/)

**Comment by dirk-thomas** [comment]
* Linux [Build Status](https://ci.ros2.org/job/ci_linux/5664/)
* Linux aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/2273/)
* macOS: [Build Status](https://ci.ros2.org/job/ci_osx/4680/) (the warnings have been addressed already, see https://github.com/ros2/rmw_opensplice/pull/247#issuecomment-442146412)
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/5553/) these warnings are still present

**Comment by dirk-thomas** [comment]
@MarcelJordense Please rebase this on top of the latest master.

**Comment by dirk-thomas** [comment]
@MarcelJordense Please rebase this on top of the latest master.

**Comment by dirk-thomas** [comment]
Can you double check the rebase? The commits as well so the diff shows changes which have already been applied to the master branch. Ideally it should only contain your modifications.

**Comment by MarcelJordense** [comment]
The cdr_serialization branch has been rebased again.

**Comment by dirk-thomas** [comment]
CI builds with only OpenSplice:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5678/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2284/) (pendulum test timing out)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4693/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5570/) (unrelated test failure, addressed in ros2/rclcpp#596)

**Comment by dirk-thomas** [comment]
Another round of CI builds:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5688/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2292/) (pendulum test timing out)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4700/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5602/) (timer test failing)

Overall this looks pretty good. I couldn't see anything wrong with the remaining failing tests and they already fail without this patch:
* Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/2296/)
* macOS [Build Status](https://ci.ros2.org/job/ci_windows/5606/)

I think we can go ahead and merge these PRs as-is. It would be great if you could continue to try resolving failing tests with OpenSplice when you have a chance. It will either resolve actual problems or at least make tests pass which will help catching future regressions.

Thanks you for implementing this and iterating on the patch!

**Pull request merged**
